import Head from "next/head";
import ProductList from "./components/ProductList";
import Navbar from "./components/Navbar";
import { useSelector } from "react-redux";

const Home = () => {
  const state = useSelector((state: any) => state.user);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar count={state.count} />
      <ProductList  />
    </>
  );
};

export default Home;
